<?php echo $this->doctype(); ?>
<html lang="pt-br" xml:lang="pt-BR">
<head>
	<?php echo $this->headTitle('titulo'); ?>
	<?php echo $this->headMeta(); ?>

	<?php /* # Rever 
	<meta name="Author" content="Apple Inc." />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta property="og:image" content="/v/home/bq/images/og.jpg?201506300850" />
	<meta property="og:type" content="website" />
	<meta property="og:site_name" content="Apple" />
	<meta property="og:url" content="https://www.apple.com/br/" />
	<meta name="Description" content="A Apple desenvolve e cria o iPhone, o iPad, os desktops e laptops Mac, o iOS 8, o OS X, o iPod e o iTunes, e o novo Apple Watch."  />
	<meta name="keywords" content="" />
	<meta name="robots" content="INDEX,FOLLOW" />
	*/
	?>

	<?php //$this->headScript()->appendFile('caminho') ?>
	<?php //$this->headScript()->appendFile('caminho', 'text/javascript', array('conditional' => 'lt IE 9')) ?>
	<?php //echo $this->headScript(); ?>

	<?php //$this->headLink()->appendStylesheet('caminho', 'screen'); ?>
	<?php //$this->headLink()->appendStylesheet('caminho', 'screen', 'IE 7' ); ?>
	<?php //echo $this->headLink(); ?>
</head>
<body>
	<?php echo $this->layout()->content; ?>
</body>
</html>

